yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: node-modules
# allow NPM_TOKEN env to be set, but provide '' as fallback. This allows CI to publish packages, but not require env var.
# See https://yarnpkg.com/configuration/yarnrc
npmAuthToken: ${NPM_TOKEN-}
npmPublishAccess: public
