# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo

version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    <<: *defaults
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Tests
          command: yarn test
      - run:
          name: Typecheck
          command: yarn typecheck

  setup_release:
    <<: *defaults
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Set Git Identity
          command: |
            git config --global user.email "ci@infinite.red"
            git config --global user.name "Infinite Red"
      - run:
          name: Set npm token
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Validate npm identity
          command: npm whoami
      - run:
          name: Release git tags and npm packages
          command: yarn release

  release_app_windows:
    <<: *defaults
    docker:
      - image: electronuserland/builder:wine
    environment:
      BUILD_TARGET: windows
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Release Windows
          command: yarn releaseApp

  release_app_nix:
    <<: *defaults
    macos:
      xcode: "13.3.1"
    environment:
      BUILD_TARGET: unix
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: cd into apps/app workspace
          command: cd apps/app
      - run:
          name: Decode Certificates
          command: 'base64 -D -o Certificates.p12 \<< $ReactotronCerts'
      - run:
          name: Install Bundler
          command: gem install bundler:1.16.1
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install Cert
          command: bundle exec fastlane setup
      - run:
          name: Install Python 3.9
          command: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install python3
      - run:
          name: Fix six conflicting file
          command: rm /usr/local/lib/python3.9/site-packages/six.py
      - run:
          name: Install Snapcraft
          command: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install snapcraft rpm
      - run:
          name: Release Mac and Linux
          command: yarn releaseApp

workflows:
  pull_request:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - master
                - beta
                - alpha

  release:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
      - setup_release:
          context:
            - infinitered-npm-package
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - build_and_test
      - release_app_windows:
          context:
            - infinitered-npm-package
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - setup_release
      - release_app_nix:
          context:
            - ReactotronCerts
            - infinitered-npm-package
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - setup_release
# VS Code Extension Version: 1.5.1
