# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo

version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    <<: *defaults
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build App
          command: yarn workspace app build
      - run:
          name: Lint
          command: yarn workspace app lint
      - run:
          name: Tests
          command: yarn workspace app test
      - run:
          name: TypeScript Compile
          command: yarn workspace app compile

  setup_release:
    <<: *defaults
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build App
          command: npx nx run-many --target build
      - run:
          name: Lint
          command: npx nx affected --target lint --base beta
      - run:
          name: Tests
          command: yarn workspace app test
      - run:
          name: TypeScript Compile
          command: yarn workspace app compile
      - run:
          name: Generate Semantic Release
          command: npx nx affected --target version
      - run:
          name: Setup workspace
          command: mkdir -p workspace
      - run:
          name: Copy everything into the workspace
          command: cp apps/app/package.json workspace/package.json
      - persist_to_workspace:
          root: workspace
          paths:
            - build
            - package.json

  release_windows:
    <<: *defaults
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Move Build and Package into the right place
          command: mv workspace/package.json package.json
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Release Windows
          command: yarn release -w

  release_nix:
    <<: *defaults
    macos:
      xcode: "13.3.1"
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Move Build and Package into the right place
          command: mv workspace/package.json package.json
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Decode Certificates
          command: 'base64 -D -o Certificates.p12 \<< $ReactotronCerts'
      - run:
          name: Install Bundler
          command: gem install bundler:1.16.1
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install Cert
          command: bundle exec fastlane setup
      - run:
          name: Install Python 3.9
          command: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install python3
      - run:
          name: Fix six conflicting file
          command: rm /usr/local/lib/python3.9/site-packages/six.py
      - run:
          name: Install Snapcraft
          command: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install snapcraft rpm
      - run:
          name: Release Mac and Linux
          command: yarn release -ml -c.snap.publish=github

workflows:
  pull_request:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - master
                - beta
                - alpha

  release:
    jobs:
      - setup_release:
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
      - release_windows:
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - setup_release
      - release_nix:
          context: ReactotronCerts
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - setup_release
# VS Code Extension Version: 1.5.1
