# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build_and_test:
    <<: *defaults
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Tests
          command: yarn test
      - run:
          name: TypeScript Compile
          command: yarn compile
      - run:
          name: Build App
          command: yarn build

  setup_release:
    <<: *defaults
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --ignore-engines
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Tests
          command: yarn test
      - run:
          name: TypeScript Compile
          command: yarn compile
      - run:
          name: Generate Semantic Release
          command: yarn semantic-release
      - save_cache:
          name: Save Release Notes
          paths:
            - build
          key: v1-release-notes

  release_windows:
    <<: *defaults
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --ignore-engines
      - restore_cache:
          name: Restore Release Notes
          keys:
            - v1-release-notes
      - run:
          name: Release Windows
          command: yarn release -w

  release_nix:
    <<: *defaults
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --ignore-engines
      - restore_cache:
          name: Restore Release Notes
          keys:
            - v1-release-notes
      - run:
          name: Decode Certificates
          command: base64 -D -o Certificates.p12 <<< $ReactotronCerts
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install Cert
          command: bundle exec fastlane setup
      - run:
          name: Install Snapcraft
          command: brew install snapcraft
      - run:
          name: Release Mac and Linux
          command: yarn release -ml

workflows:
  version: 2
  pull_request:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - master
                - beta

  release:
    jobs:
      - setup_release:
          filters:
            branches:
              only:
                - master
                - beta
      - release_windows:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - setup_release
      - release_nix:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - setup_release
